Market/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Market.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Market/Areas/Admin/Controllers/SearchController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Market.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SearchController : Controller
    {     
        private readonly MarketContext _context;
        public SearchController(MarketContext context)
        {
            _context = context;
        }
        [HttpPost]
        public IActionResult FindOrder(string keyword)
        {
            List<Order> listOrder = new List<Order>();
            if (string.IsNullOrEmpty(keyword) || keyword.Length < 1)
            {
                listOrder = _context.Orders.AsNoTracking()
                                     .Include(o => o.Employee)
                                    .Take(10)
                                    .ToList();
                if (listOrder == null)
                {
                    return PartialView("OrdersTable", null);
                }
                else
                {
                    return PartialView("OrdersTable", listOrder);
                }
            }
            listOrder = _context.Orders.AsNoTracking()
                                  .Include(o => o.Employee)
                                  .Where(x => x.OrderId.Contains(keyword) || 
                                         x.EmployeeId.Contains(keyword) ||
                                         x.CustomerName.Contains(keyword) ||
                                         x.Address.Contains(keyword) ||
                                         x.Phone.Contains(keyword))
                                  .OrderBy(x => x.OrderDate)
                                  .Take(10)
                                  .ToList();
            if (listOrder == null)
            {
                return PartialView("OrdersTable", null);
            }
            else
            {
                return PartialView("OrdersTable", listOrder);
            }
        }
		public IActionResult FilterOrderByStatus(int? TrangThai)
		{  
			var Orders = _context.Orders.Include(o => o.Employee)
			.AsNoTracking()
			.OrderBy(x => x.OrderDate);
			if (TrangThai != null && TrangThai > 0)
			{
				Orders = (IOrderedQueryable<Order>)Orders.Where(x => x.Status == TrangThai);
			}
			var searchOrder = Orders.ToList();
			return PartialView("OrdersTable", searchOrder);
		}
		public IActionResult GetPage(int page, int pageSize)
		{
			var totalRecords = _context.Orders.Include(o => o.Employee).Count();
			var pageCount = (int)Math.Ceiling((double)totalRecords / pageSize);
			if (page < 1)
			{
				page = 1;
			}
			else if (page > pageCount)
			{
				page = pageCount;
			}
			var orders = _context.Orders
				.Skip((page - 1) * pageSize)
				.Take(pageSize)
				.ToList();
			return PartialView("OrdersPaging", orders);
		}

		public IActionResult FindProduct(string keyword)
		{
			List<Product> listProducts = new List<Product>();
			if (string.IsNullOrEmpty(keyword) || keyword.Length < 1)
			{
				listProducts = _context.Products.Include(p => p.Category).Include(p => p.Supplier).AsNoTracking().Take(10).ToList();
				if (listProducts == null)
				{
					return PartialView("ProductsTable", null);
				}
				else
				{
					return PartialView("ProductsTable", listProducts);
				}
			}
			listProducts = _context.Products.Include(p => p.Category).Include(p => p.Supplier).AsNoTracking()
								.Where(x => x.ProductId.Contains(keyword) ||
										x.ProductName.Contains(keyword) ||
										x.Unit.Contains(keyword))
								.OrderBy(x => x.ProductId)
								.Take(10)
								.ToList();
			if (listProducts == null)
			{
				return PartialView("ProductsTable", null);
			}
			else
			{
				return PartialView("ProductsTable", listProducts);
			}
		}
		public IActionResult FilterProductByStatus(int? statusSearch)
		{
			var listProducts = _context.Products.Include(p => p.Category).Include(p => p.Supplier).AsNoTracking()
								.OrderBy(x => x.ProductId);
			if (statusSearch != null && statusSearch > 0)
			{
				listProducts = (IOrderedQueryable<Product>)listProducts.Where(x => x.Status == statusSearch);
			}
			var searchProduct = listProducts.ToList();
			return PartialView("ProductsTable", searchProduct);
		}
		public IActionResult FilterProductByCategory(string? category)
		{
			var listProducts = _context.Products.Include(p => p.Category).Include(p => p.Supplier).AsNoTracking()
								.OrderBy(x => x.ProductId);
			if (category != null && category.Length > 0)
			{
				listProducts = (IOrderedQueryable<Product>)listProducts.Where(x => x.CategoryId == category);
			}
			var searchProduct = listProducts.ToList();
			return PartialView("ProductsTable", searchProduct);
		}

	}
}

Market/Controllers/CartController.cs
using Market.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Market.Controllers
{
    public class CartController : Controller
    {
        private MarketContext db;
        public CartController(MarketContext context)
        {
            db = context;
        }

        

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShopingCart()
        {
            var cart = db.ShoppingCarts.Where(m => m.ShoppingCartId == "001").ToList();
            ViewBag.CartId = "001";
            return View(cart);
        }
        public IActionResult AddShopingCart(String? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = db.Products.Where(m => m.ProductId == id).FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }
            else
            {
                var cartitem = db.ShoppingCarts.Where(m => m.ProductId == id && m.ShoppingCartId == "001").FirstOrDefault();
                if (cartitem != null)
                {
                    cartitem.Amount++;
                    cartitem.Total = cartitem.Amount * cartitem.Price;
                    db.ShoppingCarts.Update(cartitem);
                }
                else if(cartitem == null)
                {
                    ShoppingCart cart = new ShoppingCart
                    {
                        Img = product.Img,
                        ProductName = product.ProductName,
                        Price = product.Price,
                        Amount = 1,
                        Unit = product.Unit,
                        ProductId = product.ProductId,
                        Total = product.Price,
                        Status = 1,
                        ShoppingCartId = "001"
                    };
                    db.ShoppingCarts.Add(cart);
                }
                db.SaveChanges();
            }
            return RedirectToAction("ShopingCart");
        }

        [HttpPost]
        public IActionResult UpdateItem(String? id,[Bind("Amount")] ShoppingCart cart)
        {
            if(id == null || db.ShoppingCarts == null)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    db.ShoppingCarts.Update(cart);
                    db.SaveChanges();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if(db.ShoppingCarts.Where(m => m.ProductId == id && m.ShoppingCartId == "001").FirstOrDefault() != null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ShopingCart");
            }
            return RedirectToAction("ShopingCart");
        }


        public IActionResult DeleteItem(String? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            else
            {
                var cartitem = db.ShoppingCarts.FirstOrDefault(m => m.ProductId == id);
                if (cartitem != null)
                {
                    db.ShoppingCarts.Remove(cartitem);
                }
                db.SaveChanges();
            }
            return RedirectToAction("ShopingCart");
        }
    }
}

Market/Controllers/HomeController.cs
using Market.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Cryptography;

namespace Market.Controllers
{
    public class HomeController : Controller
    {
        private MarketContext db;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger,MarketContext context)
        {
            _logger = logger;
            db = context;
        }
        private int pageSize = 1;

        public IActionResult Index(string? mid)
        {
            var product = (IQueryable<Product>)db.Products;
            if(mid != null)
            {
                product = (IQueryable<Product>)db.Products.Where(m => m.CategoryId == mid).Include(m => m.Category);
            }
            int pageNum = (int)Math.Ceiling(product.Count() / (float)pageSize);
            ViewBag.pageNum = pageNum;
            var result = product.Take(pageSize).ToList();
            return View(result);
        }

        public IActionResult Filter(int? pageIndex, string? keyword)
        {
            var product = (IQueryable<Product>) db.Products.Include(m => m.Category);
            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);
            if(keyword != null)
            {
                product = product.Where(l => l.CategoryId.ToLower().Contains(keyword.ToLower()));
            }
            int pageNum = (int)Math.Ceiling(product.Count() / (float)pageSize);
            ViewBag.pageNum = pageNum;
            var result = product.Skip(pageSize * (page - 1)).Take(pageSize);
            return PartialView("Search",result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Market/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model IEnumerable<Product>
<form action="#" style="margin-left:150px">
    <input type="text" placeholder="What do you need?" id="keyword">
    <button style="margin-left:30px" type="submit" class="site-btn" id="buttonSearch">SEARCH</button>
</form>
<section class="featured spad">
    <div class="container">
        <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Featured Product</h2>
                    </div>
                    <div class="featured__controls">
                        <ul>
                            <li class="active" data-filter="*">All</li>
                            <li data-filter=".oranges">Oranges</li>
                            <li data-filter=".fresh-meat">Fresh Meat</li>
                            <li data-filter=".vegetables">Vegetables</li>
                            <li data-filter=".fastfood">Fastfood</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div id="content">
            <div class="row featured__filter" id="MixItUp86281F">
                @foreach (var item in Model)
                {
                    <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
                        <div class="featured__item">
                            <div class="featured__item__pic set-bg" data-setbg="img/featured/feature-1.jpg" style="background-image: url(&quot;img/featured/feature-1.jpg&quot;);">
                                <ul class="featured__item__pic__hover">
                                    <li><a asp-controller="Cart" asp-action="AddShopingCart" asp-route-id="@item.ProductId"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <div class="featured__item__text">
                                <h6><a href="index.html#">@item.ProductName</a></h6>
                                <h5>@item.Price.Value.ToString("#,##k VND")</h5>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<ul class="pagination">
    @for (int i = 1; i <= ViewBag.pageNum; i++)
    {
        <li class="page-item" page="@i">
            <a class="page-link">@i</a>
        </li>
    }
</ul>

@section Scripts{
    <script>
        $('body').on('click', 'li.page-item', function (e) {
            var page = $(this).attr("page");
            var data = { pageIndex: page}
            $.ajax({
                url: "/Home/Filter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        $("button#buttonSearch").click(function (e) {
            var keyword = $("#keyword").val();
            var data = { keyword: keyword };
            $.ajax({
                url: "/Home/Filter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
    </script>
}

Market/Views/Home/Search.cshtml
@model IEnumerable<Product>
<div class="row featured__filter" id="MixItUp86281F">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
            <div class="featured__item">
                <div class="featured__item__pic set-bg" data-setbg="img/featured/feature-1.jpg" style="background-image: url(&quot;img/featured/feature-1.jpg&quot;);">
                    <ul class="featured__item__pic__hover">
                        <li><a asp-controller="Cart" asp-action="AddShopingCart" asp-route-id="@item.ProductId"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                </div>
                <div class="featured__item__text">
                    <h6><a href="index.html#">@item.ProductName</a></h6>
                    <h5>@item.Price</h5>
                </div>
            </div>
        </div>
    }
</div>