Market/Areas/Admin/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using Market.Models;
namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AccessController : Controller
    {
        MarketContext db = new MarketContext();
        [HttpGet]
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("UserName") == null)
            {
                return View();
            }
            else
            {
                //  return RedirectToAction("Index","Employees");
                return RedirectToAction("Index", "Home", new { area = "Admin" });

            }

        }
        [HttpPost]   
        public IActionResult Login(User user)
        {
            if (HttpContext.Session.GetString("UserName") == null)
            {
                // Xác minh tên đăng nhập và mật khẩu
                var u = db.Users
                    .Where(x => x.UserName.Equals(user.UserName) && x.Password.Equals(user.Password) && x.Status == 1)
                    .FirstOrDefault();

                if (u != null)
                {
                    HttpContext.Session.SetString("UserName", user.UserName);
                    // Đăng nhập thành công, chuyển hướng đến trang Employees
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else
                {
                    // Trạng thái tài khoản không hợp lệ hoặc tài khoản không tồn tại, hiển thị thông báo lỗi
                    ViewBag.ErrorMessage = "Tài khoản của bạn không hợp lệ hoặc không tồn tại.";
                    return View();
                }
            }
            return View();
        }

    }
}

Market/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Market.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Market.Areas.Admin.Helpers;
using System.Security.Cryptography;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;

        private readonly MarketContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductsController(MarketContext context, IWebHostEnvironment webHostEnvironment, ILogger<ProductsController> logger)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }


        public async Task<string> GetImageNameById(string productId)
        {
            // Thực hiện truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm dựa trên ProductId
            var product = await _context.Products.FindAsync(productId);

            if (product != null)
            {
                // Lấy tên tệp ảnh từ đối tượng sản phẩm
                string imageName = product.Img;

                return imageName;
            }

            // Trả về null nếu không tìm thấy sản phẩm với ProductId tương ứng
            return null;
        }


        // GET: Admin/Products

        private int pageSize = 3;

        [Route("Admin/Products/Index")]
        public async Task<IActionResult> Index(int? s, string? cid)
        {
            var products = (IQueryable<Product>)_context.Products.Include(p => p.Category).Include(p => p.Supplier);

            if (s != null)
            {
                products = (IQueryable<Product>)_context.Products.Where(x => x.Status == s).Include(p => p.Category).Include(p => p.Supplier);
            }
            if (cid != null)
            {
                products = (IQueryable<Product>)_context.Products.Where(x => x.CategoryId == cid).Include(p => p.Category).Include(p => p.Supplier);
            }
            // tính số trang 
            int pageNum = (int)Math.Ceiling(products.Count() / (float)pageSize);

            // trả số trang về view để hiển thị nav-trang
            ViewBag.pageNum = pageNum;

            //lấy dữ liệu trang đầu
            var result = products.Take(pageSize).ToList();

            ViewBag.CategoryId = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            List<SelectListItem> listStatus = ProductStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;

            return View(result);
        }
        public IActionResult ProductFilter(int? s, string? cid, string? keyword, int? pageIndex)
        {
            // lấy toàn bộ listproduct trong dbset chuyển về IQueryable<Product> để query
            var products = (IQueryable<Product>)_context.Products;

            // lấy chỉ số trang
            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);

            // lọc product nếu có s
            if (s != null && s != 0)
            {
                //lọc
                products = products.Where(x => x.Status == s);

                // gửi s về view để ghi lại trên nav-phân trang
                ViewBag.s = s;
            }
            // lọc theo cid
            if (cid != null && cid != "")
            {
                products = products.Where(x => x.CategoryId == cid);
                ViewBag.cid = cid;
            }
            if (keyword != null && keyword != "")
            {
                products = products.Where(x => x.ProductId.ToLower().Contains(keyword.ToLower()) ||
                                                x.ProductName.ToLower().Contains(keyword.ToLower()) ||
                                                x.Unit.ToLower().Contains(keyword.ToLower()) ||
                                                x.Supplier.SupplierName.ToLower().Contains(keyword.ToLower()));

                ViewBag.keyword = keyword;
            }

            // tính số trang 
            int pageNum = (int)Math.Ceiling(products.Count() / (float)pageSize);

            // gửi về view
            ViewBag.pageNum = pageNum;

            // chọn dữ liệu trong trang hiện tại 
            var result = products.Skip(pageSize * (page - 1)).Take(pageSize).Include(p => p.Category).Include(p => p.Supplier);

            return PartialView("ProductTable", result);
        }

        // GET: Admin/Products/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }


        // GET: Admin/Products/Create
        public IActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_context.Categories.Where(c => c.Status == 1), "CategoryId", "CategoryName");

            List<SelectListItem> listStatus = ProductStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;

            /*ViewData["SupplierId"] = new SelectList(_context.Suppliers, "Suppliers", "SupplierId");*/
            ViewBag.SupplierId = new SelectList(_context.Suppliers.Where(s => s.Status == 1), "SupplierId", "SupplierName");
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,Unit,Price,Amount,SupplierId,CategoryId,Img,Detail,Status")] Product product, IFormFile imgFile)
        {
            if (_context.Products.Any(p => p.ProductId == product.ProductId))
            {
                ModelState.AddModelError("ProductId", "Mã sản phẩm đã tồn tại.");
                List<SelectListItem> lstatus = ProductStatusHelper.GetStatusList();
                ViewBag.Status = lstatus;
                return View(product);
            }
            if (ModelState.IsValid)
            {
                if (imgFile != null && imgFile.Length > 0)
                {
                    string id = product.ProductId.ToString();
                    string fileName = "";

                    int index = imgFile.FileName.IndexOf('.');
                    fileName = "product" + id + "." + imgFile.FileName.Substring(index + 1);
                    string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "img", "product");
                    string filePath = Path.Combine(uploadFolder, fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await imgFile.CopyToAsync(fileStream);
                    }
                    product.Img = fileName;
                }

                _context.Add(product);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Sản phẩm đã được thêm thành công!";
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CategoryId = new SelectList(_context.Categories.Where(c => c.Status == 1), "CategoryId", "CategoryName");

            List<SelectListItem> listStatus = ProductStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;

            ViewBag.SupplierId = new SelectList(_context.Suppliers.Where(s => s.Status == 1), "SupplierId", "SupplierName");
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.CategoryId = new SelectList(_context.Categories.Where(c => c.Status == 1), "CategoryId", "CategoryName");

            ViewBag.SupplierId = new SelectList(_context.Suppliers.Where(s => s.Status == 1), "SupplierId", "SupplierName");

            List<SelectListItem> listStatus = ProductStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;
            return View(product);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ProductId,ProductName,Unit,Price,Amount,SupplierId,CategoryId,Img,Detail,Status")] Product product, IFormFile picture)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            /*string oldFileName = product.Img; // Lưu tên file cũ*/

            if (picture != null && picture.Length > 0)
            {
                string imgName = "";
                int index = picture.FileName.LastIndexOf('.');
                imgName = "product" + id + "." + picture.FileName.Substring(index + 1);
                string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "img", "product");

Market/Areas/Admin/Views/Shared/Footer.cshtml
<footer class="footer">
    <div class="footer-content">
        <p class="m-b-0">Copyright © 2019 Theme_Nate. All rights reserved.</p>
        <span>
            <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
            <a href="" class="text-gray">Privacy &amp; Policy</a>
        </span>
    </div>
</footer>

Market/Areas/Admin/Views/Shared/Header.cshtml
<div class="header">
    <div class="logo logo-dark">
        <a href="index.html">
            <img src="~/adminassets/images/logo/logo.png" alt="Logo">
            <img class="logo-fold" src="~/adminassets/images/logo/logo-fold.png" alt="Logo">
        </a>
    </div>
    <div class="logo logo-white">
        <a href="index.html">
            <img src="~/adminassets/images/logo/logo-white.png" alt="Logo">
            <img class="logo-fold" src="~/adminassets/images/logo/logo-fold-white.png" alt="Logo">
        </a>
    </div>
    <div class="nav-wrap">
        <ul class="nav-left">
            <li class="desktop-toggle">
                <a href="javascript:void(0);">
                    <i class="anticon"></i>
                </a>
            </li>
            <li class="mobile-toggle">
                <a href="javascript:void(0);">
                    <i class="anticon"></i>
                </a>
            </li>
        </ul>
        <ul class="nav-right">
            <li class="dropdown dropdown-animated scale-left">
                <a href="javascript:void(0);" data-toggle="dropdown">
                    <i class="anticon anticon-bell notification-badge"></i>
                </a>
                <div class="dropdown-menu pop-notification">
                    <div class="p-v-15 p-h-25 border-bottom d-flex justify-content-between align-items-center">
                        <p class="text-dark font-weight-semibold m-b-0">
                            <i class="anticon anticon-bell"></i>
                            <span class="m-l-10">Notification</span>
                        </p>
                        <a class="btn-sm btn-default btn" href="javascript:void(0);">
                            <small>View All</small>
                        </a>
                    </div>
                    <div class="relative">
                        <div class="overflow-y-auto relative scrollable" style="max-height: 300px">
                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                <div class="d-flex">
                                    <div class="avatar avatar-blue avatar-icon">
                                        <i class="anticon anticon-mail"></i>
                                    </div>
                                    <div class="m-l-15">
                                        <p class="m-b-0 text-dark">You received a new message</p>
                                        <p class="m-b-0"><small>8 min ago</small></p>
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                <div class="d-flex">
                                    <div class="avatar avatar-cyan avatar-icon">
                                        <i class="anticon anticon-user-add"></i>
                                    </div>
                                    <div class="m-l-15">
                                        <p class="m-b-0 text-dark">New user registered</p>
                                        <p class="m-b-0"><small>7 hours ago</small></p>
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                <div class="d-flex">
                                    <div class="avatar avatar-red avatar-icon">
                                        <i class="anticon anticon-user-add"></i>
                                    </div>
                                    <div class="m-l-15">
                                        <p class="m-b-0 text-dark">System Alert</p>
                                        <p class="m-b-0"><small>8 hours ago</small></p>
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 ">
                                <div class="d-flex">
                                    <div class="avatar avatar-gold avatar-icon">
                                        <i class="anticon anticon-user-add"></i>
                                    </div>
                                    <div class="m-l-15">
                                        <p class="m-b-0 text-dark">You have a new update</p>
                                        <p class="m-b-0"><small>2 days ago</small></p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <li class="dropdown dropdown-animated scale-left">
                <div class="pointer" data-toggle="dropdown">
                    <div class="avatar avatar-image  m-h-10 m-r-15">
                        <img src="~/adminassets/images/avatars/thumb-3.jpg" alt="">
                    </div>
                </div>
                <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                    <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                        <div class="d-flex m-r-50">
                            <div class="avatar avatar-lg avatar-image">
                                <img src="~/adminassets/images/avatars/thumb-3.jpg" alt="">
                            </div>
                            <div class="m-l-10">
                                <p class="m-b-0 text-dark font-weight-semibold">Marshall Nichols</p>
                                <p class="m-b-0 opacity-07">UI/UX Desinger</p>
                            </div>
                        </div>
                    </div>
                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                        <div class="d-flex align-items-center justify-content-between">
                            <div>
                                <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                <span class="m-l-10">Edit Profile</span>
                            </div>
                            <i class="anticon font-size-10 anticon-right"></i>
                        </div>
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                        <div class="d-flex align-items-center justify-content-between">
                            <div>
                                <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                <span class="m-l-10">Account Setting</span>
                            </div>
                            <i class="anticon font-size-10 anticon-right"></i>
                        </div>
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                        <div class="d-flex align-items-center justify-content-between">
                            <div>
                                <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                <span class="m-l-10">Projects</span>
                            </div>
                            <i class="anticon font-size-10 anticon-right"></i>
                        </div>
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                        <div class="d-flex align-items-center justify-content-between">
                            <div>
                                <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                <span class="m-l-10">Logout</span>
                            </div>
                            <i class="anticon font-size-10 anticon-right"></i>
                        </div>
                    </a>
                </div>
            </li>

        </ul>
    </div>
</div>

Market/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin Dashboard Template</title>

    <!-- Favicon -->
	<link rel="shortcut icon" href="~/adm
    <!-- page css -->
    <link href="~/adminassets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet">

    <!-- NTH -->
    <style>
        /* CSS để chỉnh màu chữ và kích thước chữ */
        .custom-productName {
            color: black;
            font-size: 14px;
        }

            /* CSS để chỉnh màu chữ khi hover */
            .custom-productName:hover {
                color: blue;
            }

        textarea {
            overflow-y: hidden;
            overflow-x: hidden;
            height: auto;
        }

    </style>

    <!-- Core css -->
    <link href="~/adminassets/css/app.min.css" rel="stylesheet">
    <link href="~/adminassets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" />
    <script src="~/adminassets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            @await Html.PartialAsync("Header.cshtml");
            <!-- Header END -->
            <!-- Side Nav START -->
            @await Html.PartialAsync("_SideNavPartialView.cshtml");
            <!-- Side Nav END -->
            <!-- Page Container START -->
            <div class="page-container">

                <!-- Content Wrapper START -->
                <div class="main-content">
                    @RenderBody()
                </div>
                <!-- Content Wrapper END -->
                <!-- Footer START -->
                @await Html.PartialAsync("Footer.cshtml");
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->
            <!-- Quick View START -->
            <!-- Quick View END -->
        </div>
    </div>

    <script src="~/admin~/adminassets/js/vendors.min.js"></script>
    <!-- Core Vendors JS -->
    <script src="~/adminassets/js/vendors.min.js"></script>

    <!-- page js -->
    <script src="~/adminassets/vendors/chartjs/Chart.min.js"></script>
    <script src="~/adminassets/js/pages/dashboard-e-commerce.js"></script>

    <!-- Core JS -->
    <script src="~/adminassets/js/app.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts",required:false) 
    @await RenderSectionAsync("Paginate",required: false)
    @await RenderSectionAsync("upload", required: false)
    @await RenderSectionAsync("ScriptsCT", required: false)
    @RenderSection("Users", required:false);
</body>

</html>

Market/Areas/Admin/Views/Shared/_SideNavPartialView.cshtml
<div class="side-nav">
    <div class="side-nav-inner">
        <ul class="side-nav-menu scrollable">
            <li class="nav-item">
                <a class="dropdown-toggle" asp-area="Admin" asp-controller="Home" asp-action="Index">
                    <span class="icon-holder">
                        <i class="anticon anticon-dashboard"></i>
                    </span>
                    <span class="title">Trang chủ</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>

            </li>
            <li class="nav-item dropdown">
                <a asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
                    <span class="icon-holder">
                        <i class="anticon anticon-appstore"></i>
                    </span>
                    <span class="title">Quản lý đơn hàng</span>

                </a>

            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title">Quản lý sản phẩm</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-area="Admin" asp-controller="Products" asp-action="Index">Danh sách sản phẩm</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Categories" asp-action="Index">Quản lý danh mục sản phẩm</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Suppliers" asp-action="Index">Quản lý nhà cung cấp</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title">Quản lý nhân viên</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-area="Admin" asp-controller="Employees" asp-action="Index">Danh sách nhân viên</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Users" asp-action="Index">Tài khoản hệ thống</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-form"></i>
                    </span>
                    <span class="title">Báo cáo thống kê</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="form-elements.html">Doanh thu</a>
                    </li>
                    <li>
                        <a href="form-layouts.html">Tồn kho</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" asp-area="Admin" asp-controller="Access" asp-action="Login">
                    <span class="icon-holder">
                        <i class="anticon anticon-table"></i>
                    </span>
                    <span class="title">Đăng xuất</span>
                </a>
            </li>
        </ul>
    </div>
</div>