Market/Areas/Admin/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Market.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminOrdersController : Controller
    {
        private readonly MarketContext _context;
        public INotyfService _notyfService { get; }

        public AdminOrdersController(MarketContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
		private int pageSize = 3;
		public IActionResult Index()
        {    
            var orders = (IQueryable<Order>)_context.Orders.Include(o => o.Employee)
                .OrderBy(x => x.OrderDate);
			// Tính số trang
			int pageNum = (int)Math.Ceiling(orders.Count() / (float)pageSize);
			// Trả về số trang hiển thị trong nav-trang
			ViewBag.pageNum = pageNum;
			// Lấy dữ liệu trang đầu
			var result = orders.Take(pageSize).ToList();

			List<SelectListItem> listTrangThai = new List<SelectListItem>();
            listTrangThai.Add(new SelectListItem() { Text = "Chờ xác nhận", Value = "1" });
            listTrangThai.Add(new SelectListItem() { Text = "Đã xác nhận", Value = "2" });
            listTrangThai.Add(new SelectListItem() { Text = "Đã hủy đơn", Value = "3" });
            listTrangThai.Add(new SelectListItem() { Text = "Đã giao", Value = "4" });
            ViewData["TrangThaiDonHang"] = listTrangThai;

            return View(result);
        }
		public IActionResult FilterOrder(int? status, string keyword, int? pageIndex)
		{
			var orders = (IQueryable<Order>)_context.Orders.Include(o=>o.Employee)
				                     .AsNoTracking()
                                     .OrderBy(x => x.OrderDate);
			int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);
			if (status != null && status>0)
			{
				orders = orders.Where(m => m.Status == status);
				ViewBag.status = status;
			}
			if (keyword != null)
			{
                orders = (IOrderedQueryable<Order>)orders.Where(x => 
                                         x.OrderId.Contains(keyword) ||
										 x.EmployeeId.Contains(keyword) ||
										 x.CustomerName.Contains(keyword) ||
										 x.Address.Contains(keyword) ||
										 x.Phone.Contains(keyword));
				ViewBag.keyword = keyword;
			}
			int pageNum = (int)Math.Ceiling(orders.Count() / (float)pageSize);
			ViewBag.pageNum = pageNum;
			var result = orders
				.Skip(pageSize * (page - 1))
				.Take(pageSize)
				.Include(m => m.Employee)
                .OrderBy(m=>m.OrderDate);
			return PartialView("OrdersPaging", result);
		}

		public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
            .Include(o => o.Employee)
            .Include(o => o.OrderDetails)
            .ThenInclude(od => od.Product)
            .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            var orderDetails = order.OrderDetails.ToList();

            var productNames = orderDetails.Select(od => od.Product.ProductName).ToList();

            ViewData["ProductNames"] = productNames;
            ViewBag.Details = orderDetails;
            return View(order);
        }
		public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,EmployeeId,Status,OrderDate,TotalOrders,CustomerName,Address,Phone,Note")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
				_notyfService.Success("Thêm mới thành công");
				return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", order.EmployeeId);
            return View(order);
        }
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", order.EmployeeId);
            List<SelectListItem> listTrangThai = new List<SelectListItem>();
            listTrangThai.Add(new SelectListItem() { Text = "Chờ xác nhận", Value = "1" });
            listTrangThai.Add(new SelectListItem() { Text = "Đã xác nhận", Value = "2" });
            listTrangThai.Add(new SelectListItem() { Text = "Đã hủy đơn", Value = "3" });
            listTrangThai.Add(new SelectListItem() { Text = "Đã giao", Value = "4" });
            ViewData["TrangThaiDonHang"] = listTrangThai;
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("OrderId,EmployeeId,Status,OrderDate,TotalOrders,CustomerName,Address,Phone,Note")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
					_notyfService.Success("Cập nhật thành công");
				}
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", order.EmployeeId);
            
            return View(order);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Employee)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'MarketContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
			_notyfService.Success("Hủy hóa đơn thành công");
			return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(string id)
        {
          return (_context.Orders?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }
    }
}

Market/Areas/Admin/Views/AdminOrders/Create.cshtml
@model Market.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class ="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalOrders" class="control-label"></label>
                <input asp-for="TotalOrders" class="form-control" />
                <span asp-validation-for="TotalOrders" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
        <i class="anticon anticon-arrow-left m-r-5"></i>
        <span>Quay lại</span>
    </a>
</div>

Market/Areas/Admin/Views/AdminOrders/Delete.cshtml
@model Market.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalOrders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalOrders)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.EmployeeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
            <i class="anticon anticon-arrow-left m-r-5"></i>
            <span>Quay lại</span>
        </a>
    </form>
</div>

Market/Areas/Admin/Views/AdminOrders/Details.cshtml
@model Market.Models.Order

@{
    ViewData["Title"] = "Thông tin đơn hàng #" + Model.OrderId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.Details;
}


<div class="page-header">
    <h2 class="header-title"></h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminOrders" asp-action="Home" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Chi tiết đơn hàng</span>
        </nav>
    </div>
</div>

<div class="container">
    <div class="card">
        <div class="card-body">
            <div id="invoice" class="p-h-30">
                <div class="row m-t-20 lh-2">
                    <div class="col-sm-6">
                        <h3 class="p-l-10 m-t-10">THÔNG TIN ĐƠN HÀNG:</h3>
                        <address class="p-l-10 m-t-10">
                            <p><span class="font-weight-semibold text-dark">Họ và Tên:</span> @Model.CustomerName</p>
                            <p><span class="font-weight-semibold text-dark">Địa chỉ:</span> @Model.Address</p>
                            <p><span class="font-weight-semibold text-dark">Số điện thoại:</span> @Model.Phone</p>
                            <p><span class="font-weight-semibold text-dark">Mã đơn hàng:</span> @Model.OrderId</p>
                            <p><span class="font-weight-semibold text-dark">Ngày đặt hàng:</span> @Model.OrderDate</p>
                            
                                @if (Model.Status == 1)
                                {
                                   <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Chờ xác nhận </p>
                                }
                                else if (Model.Status == 2)
                                {
                                   <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Đã xác nhận </p>
                                }
                                else if (Model.Status == 3)
                                {
                                   <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Đã hủy </p>
                                }
                                else if (Model.Status == 4)
                                {
                                   <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Đã giao </p>
                                }
                            
                        </address>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <div>
                        <a
                            class="btn btn-primary" asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Create">
                            <i class="anticon anticon-plus-circle m-r-5"></i>
                            <span>Thêm sản phẩm</span>
                        </a>
                    </div>
                </div>
                <div class="m-t-20">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Mã hóa đơn</th>
                                    <th>Tên vật phẩm</th>
                                    <th>Số lượng</th>
                                    <th>Đơn giá bán</th>
                                    <th>Giảm giá</th>
                                    <th>Thành tiền</th>
                                    <th>Thao tác</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (orderDetails != null && orderDetails.Count() > 0)
                                {
                                    @for (var i = 0; i < orderDetails.Count(); i++)
                                    {
                                        <tr>
                                            <th>@orderDetails[i].OrderId</th>
                                            <td>@orderDetails[i].Product.ProductName</td>
                                            <td>@orderDetails[i].Amount</td>
                                            <td>@orderDetails[i].Price.Value.ToString("#,##0 VNĐ")</td>
                                            <td>@orderDetails[i].Sale</td>
                                            <td>@orderDetails[i].Total.Value.ToString("#,##0 VNĐ")</td>
                                            <td>
                                                <a asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Edit" asp-route-id="@orderDetails[i].OrderId"> <i class="anticon anticon-edit"></i></a>
                                                <a asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Delete" asp-route-id="@orderDetails[i].OrderId"><i class="anticon anticon-delete"></i></a>
                                            </td>
                                        </tr>
                                    };
                                    
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="row m-t-30 lh-1-8">
                        <div class="col-sm-12">
                            <div class="float-right text-right">
                                <h3>Tổng tiền: @Model.TotalOrders.Value.ToString("#,##0 VNĐ")</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Market/Areas/Admin/Views/AdminOrders/Edit.cshtml
@model Market.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="ViewBag.TrangThaiDonHang"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalOrders" class="control-label"></label>
                <input asp-for="TotalOrders" class="form-control" />
                <span asp-validation-for="TotalOrders" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
        <i class="anticon anticon-arrow-left m-r-5"></i>
        <span>Quay lại</span>
    </a>
</div>

Market/Areas/Admin/Views/AdminOrders/Index.cshtml
@{
	ViewData["Title"] = "Danh sách đơn hàng";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@model IEnumerable<Order>
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<span class="breadcrumb-item active">Danh sách đơn hàng</span>
		</nav>
	</div>
</div>
<div class="row m-b-30">
	<div class="col-lg-3 col-md-3 col-sm-12">
		<div class="input-affix m-v-10">
			<select class="custom-select" id="txtStatus" name="txtStatus" asp-items="ViewBag.TrangThaiDonHang">
				<option selected>Chọn trạng thái</option>
				<option value="0">Tất cả</option>
			</select>
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-sm-12">
		<div class="input-affix m-v-10">
			<label>Thời gian từ</label>
			<input type="text" class="form-control datepicker-input" name="start" placeholder="From">
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-sm-12">
		<div class="input-affix m-v-10">
			<label>Thời gian đến</label>
			<input id="td" type="text" class="form-control datepicker-input" name="end" placeholder="To">
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-sm-12">
		<div class="text-right">
			<a class="btn btn-primary" asp-area="Admin" asp-controller="AdminOrders" asp-action="Create">
				<i class="anticon anticon-plus-circle m-r-5"></i>
				<span>Tạo đơn hàng</span>
			</a>
		</div>
	</div>
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-6">
				<div class="input-affix m-v-10">
					<i class="prefix-icon anticon anticon-search opacity-04"></i>
					<input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm đơn hàng">
				</div>
			</div>
			<div class="col-md-6">
				<div class="input-affix m-v-10">
					<button id="btnSearch" class="btn btn-danger m-r-5"><i class="anticon anticon-search"></i> Tìm kiếm</button>
					<button id="btnRefresh" class="btn btn-default m-r-5"><i class="anticon anticon-reload"></i> Làm lại</button>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="paging" class="table-responsive">
	<table class="table table-hover e-commerce-table">
		<thead>
			<tr>
				<th>Mã hóa đơn</th>
				<th>Mã nhân viên</th>
				<th>Trạng thái đơn hàng</th>
				<th>Ngày tạo đơn</th>
				<th>Tổng tiền</th>
				<th>Thao tác</th>
			</tr>
		</thead>
		<tbody id="searchOrder">
			@if (Model != null)
			{
				foreach (var item in Model)
				{

					<tr>
						<td>
							<a class="link m-r-5" asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Index" asp-route-id="@item.OrderId">@item.OrderId</a>
						</td>
						<td>@item.EmployeeId</td>
						<td>
							@if (item.Status==1)
							{
								<div class="d-flex align-items-center">
									<div class="badge badge-danger badge-dot m-r-10"></div>
									<div>Chờ xác nhận</div>
								</div>
							}
							else if (item.Status == 2)
							{
								<div class="d-flex align-items-center">
									<div class="badge badge-success badge-dot m-r-10"></div>
									<div>Đã xác nhận</div>
								</div>
							}
							else if (item.Status == 3)
							{
								<div class="d-flex align-items-center">
									<span class="status-icon">&#x2718;</span>
									<div>Đã hủy đơn</div>
								</div>
							}
							else if (item.Status == 4)
							{
								<div class="d-flex align-items-center">
									<span class="status-icon">&#x2714;</span>
									<div>Đã giao</div>
								</div>
							}
						</td>
						<td>@item.OrderDate</td>
						<td>@item.TotalOrders VNĐ</td>
						<td>
							<a class="btn btn-outline-primary m-r-5" asp-area="Admin" asp-controller="AdminOrders" asp-action="Edit" asp-route-id="@item.OrderId">Chỉnh sửa</a>
							<a class="btn btn-outline-primary m-r-5" asp-area="Admin" asp-controller="AdminOrders" asp-action="Delete" asp-route-id="@item.OrderId">Xóa</a>
						</td>
					</tr>
				}
			}
		</tbody>

	</table>
	<ul class="pagination m-l-20 m-t-5">
			@for (int i = 1; i <= ViewBag.pageNum; i++)
			{
				<li class="page-item active" page="@i"
			    @(ViewBag.status != null ? "status='@ViewBag.status'" : "")
				@(ViewBag.keyword != null ? "keyword='@ViewBag.keyword'" : "") >
				<a class="page-link" style="border-radius: 5px;">@i</a>
				</li>
			}
		</ul>
</div>

@* @section Scripts{
	<script>
		$(document).ready(function () {
			$("#btnSearch").click(function () {
				//var status = $(this).val();
				var idSearch = $('#keyword').val();
				$.ajax({
					url: '/Admin/Search/FindOrder/',
					datatype: "json",
					type: "POST",
					data: {
						keyword: idSearch
					},
					async: true,
					success: function (results) {
						$("#searchOrder").html("");
						$("#searchOrder").html(results)
					},
					error: function (xhr) {
						alert('error')
					}
				});x
			});
			$("#btnRefresh").click(function () {
				window.location.href = '/Admin/AdminOrders/Index';
			});

			$("#txtStatus").change(function () {
				var selectedStatus = $(this).val();
				$.ajax({
					url: '/Admin/Search/FilterOrderByStatus',
					datatype: "json",
					type: "GET",
					data: {
						TrangThai: selectedStatus
					},
					async: true,
					success: function (results) {
						$("#searchOrder").html("");
						$("#searchOrder").html(results);
					},
					error: function (xhr) {
						alert('error');
					}
				});
			});
			
		});
	</script>
}
 *@
@section Scripts{
	<script>
		function filterOrders(pageIndex) {
			var status = $('#txtStatus').val() || '';
			var keyword = $('#keyword').val() || '';
			var data = {
				status: status,
				keyword: keyword,
				pageIndex: pageIndex || ''
			};
			$.ajax({
				url: '/Admin/AdminOrders/FilterOrder',
				data: data,
				success: function (results) {
					$("div#paging").html(results);
				}
			});
		}
		$('body').on('click', 'li.page-item', function (e) {
			var page = $(this).attr("page");
			filterOrders(page);
		});
		$("#txtStatus").change(function () {
			filterOrders();
		});
		$("#btnSearch").click(function (e) {
			filterOrders();
		});


		$("#btnRefresh").click(function () {
			window.location.href = '/Admin/AdminOrders/Index';
		});
		$(document).ready(function () {
			$('.datepicker-input').datepicker();
		});


	</script>
}